name: Build Windows EXE

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            echo "openpyxl" > requirements.txt
            pip install -r requirements.txt
          }
        shell: powershell

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed ^
            --hidden-import=tabs.tab1_template ^
            --hidden-import=tabs.tab2_entry ^
            --hidden-import=excel_utils ^
            --name "不良品データ管理システム" ^
            --icon=icon.ico main.py
        shell: cmd
        continue-on-error: true

      - name: Build EXE without icon (fallback)
        if: failure()
        run: |
          pyinstaller --onefile --windowed --name "不良品データ管理システム" main.py
        shell: cmd

      - name: List dist contents
        run: dir dist
        shell: cmd

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
