name: Build Windows EXE

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install openpyxl
          pip install -r requirements.txt
        continue-on-error: true

      - name: Create requirements.txt if not exists
        run: |
          if (!(Test-Path requirements.txt)) {
            echo "openpyxl" > requirements.txt
          }
        shell: powershell

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name "不良品データ管理システム" --icon=icon.ico main.py
        continue-on-error: false

      - name: Build EXE without icon (fallback)
        if: failure()
        run: |
          pyinstaller --onefile --windowed --name "不良品データ管理システム" main.py

      - name: List dist contents
        run: |
          dir dist
        shell: cmd

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/*.exe

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-console:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install openpyxl
          pip install -r requirements.txt
        continue-on-error: true

      - name: Create requirements.txt if not exists
        run: |
          if (!(Test-Path requirements.txt)) {
            echo "openpyxl" > requirements.txt
          }
        shell: powershell

      - name: Build Console EXE with PyInstaller
        run: |
          pyinstaller --onefile --console --name "不良品データ管理システム-console" main.py

      - name: Upload Console EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-console-exe
          path: dist/*.exe
